
name: Stability Deployment

on:
  
  push:
    branches: [ single_user ]

jobs:
 
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port:  ${{ secrets.PORT }}
        script: |
          cd ~/stability-ai-with-token-system
          git pull origin single_user
          git status
          source ~/stability-ai-with-token-system/venv/bin/activate
          python manage.py collectstatic --no-input
          sudo systemctl restart gunicorn_stability
          sudo systemctl restart nginx